---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:

  - name: Install Required Packages
    package:
      - qemu-guest-agent
      - net-tools

  - name: Ensure QEMU is running
    systemd_service:
      state: started
      enabled: true
      name: qemu-guest-agent