---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:

  - name: Create directory
    file:
      path: /root/ansible_worked
      state: directory
      mode: '0700'