---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:

  - name: create dir
    file:
      state: directory
      path: /root/ansible-worked

  - name: install packages
    package:
      name:
        - qemu-guest-agent
      state: latest

  - name: ensure qemu is running
    systemd_service:
      state: started
      name: qemu-guest-agent
      enabled: true