---
- name: Copy Canal file to clean up NetworkManager
  ansible.builtin.copy:
    src: rke2-canal
    dest: /etc/NetworkManager/conf.d/rke2-canal.conf

- name: Restart NetworkManager
  ansible.builtin.systemd_service:
    state: restarted
    name: NetworkManager